### ISSUE TITLE
Can't specify precision in to_maiden

### ISSUE THREAD

**Issue by djboulet** [space-physics/maidenhead#5]
I get  TypeError when trying to specify a precision.

Python 3.7.7 (default, Apr 23 2020, 14:54:40) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import maidenhead as mh
>>> mh.to_maiden(45.0,-75.0)
'FN25ma'
>>> mh.to_maiden(45.0,-75.0,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: to_maiden() takes from 1 to 2 positional arguments but 3 were given
>>>

Am I missing something obvious?

**Comment by scivision** [comment]
Thanks, I made precision a positional argument now.
